# coding: utf-8

"""
    Jobs API 2.1

    The Jobs API allows you to create, edit, and delete jobs. You should never hard code secrets or store them in plain text. Use the [Secrets API](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/secrets) to manage secrets in the [Databricks CLI](https://docs.microsoft.com/azure/databricks/dev-tools/cli/index). Use the [Secrets utility](https://docs.microsoft.com/azure/databricks/dev-tools/databricks-utils#dbutils-secrets) to reference secrets in notebooks and jobs.  # noqa: E501

    The version of the OpenAPI document: 2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr


class TerminationParameter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    username: Optional[StrictStr] = Field(
        None, description="The username of the user who terminated the cluster."
    )
    azure_error_code: Optional[StrictStr] = Field(
        None,
        description="The Azure provided error code describing why cluster nodes could not be provisioned. For reference, see: [https://docs.microsoft.com/azure/virtual-machines/windows/error-messages](https://docs.microsoft.com/azure/virtual-machines/windows/error-messages).",
    )
    azure_error_message: Optional[StrictStr] = Field(
        None,
        description="Human-readable context of various failures from Azure. This field is unstructured, and its exact format is subject to change.",
    )
    databricks_error_message: Optional[StrictStr] = Field(
        None,
        description="Additional context that may explain the reason for cluster termination. This field is unstructured, and its exact format is subject to change.",
    )
    inactivity_duration_min: Optional[StrictStr] = Field(
        None,
        description="An idle cluster was shut down after being inactive for this duration.",
    )
    instance_id: Optional[StrictStr] = Field(
        None, description="The ID of the instance that was hosting the Spark driver."
    )
    instance_pool_id: Optional[StrictStr] = Field(
        None, description="The ID of the instance pool the cluster is using."
    )
    instance_pool_error_code: Optional[StrictStr] = Field(
        None,
        description="The [error code](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/clusters#clusterterminationreasonpoolclusterterminationcode) for cluster failures specific to a pool.",
    )
    __properties = [
        "username",
        "azure_error_code",
        "azure_error_message",
        "databricks_error_message",
        "inactivity_duration_min",
        "instance_id",
        "instance_pool_id",
        "instance_pool_error_code",
    ]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TerminationParameter:
        """Create an instance of TerminationParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TerminationParameter:
        """Create an instance of TerminationParameter from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return TerminationParameter.parse_obj(obj)

        _obj = TerminationParameter.parse_obj(
            {
                "username": obj.get("username"),
                "azure_error_code": obj.get("azure_error_code"),
                "azure_error_message": obj.get("azure_error_message"),
                "databricks_error_message": obj.get("databricks_error_message"),
                "inactivity_duration_min": obj.get("inactivity_duration_min"),
                "instance_id": obj.get("instance_id"),
                "instance_pool_id": obj.get("instance_pool_id"),
                "instance_pool_error_code": obj.get("instance_pool_error_code"),
            }
        )
        return _obj
